version: '3.7'

services:
  app:
    container_name: orpen-weather
    build: .
    restart: always
    volumes:
      - .:/user/src/app
    depends_on:
      - mongodb_container
    ports:
      - 3001:3001
    command: npm run dev

  mongodb_container:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: orpen
      MONGO_INITDB_ROOT_PASSWORD: openweathermapAPI
      MONGO_INITDB_DATABASE: orpenDB

volumes:
  mongodb_data_container:

networks:
  app-network:
    driver: bridge
