version: '3.7'

services:
  app:
    container_name: orpen-weather
    build: .
    env_file:
      - .env
    volumes:
      - .:/user/src/app
    depends_on:
      - mongodb_container
    ports:
      - 3001:3001
    command: npm run dev

networks:
  app-network:
    driver: bridge
