version: '3.7'

services:
  app:
    container_name: orpen-weather
    build: .
    environment:
      - DATABASE_URL=mongodb+srv://diogo254:kInjCdD7rcLiy7FM@cluster0.rxzkzzr.mongodb.net/cluster0?retryWrites=true&w=majority
      - KEY_WEATHER=d81e162ef8df5d5b622c6337b2e82a74
    volumes:
      - .:/user/src/app
    ports:
      - 3001:3001
    command: npm start

networks:
  app-network:
    driver: bridge
